namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_AWS_PROJECT_REGION: string
    NEXT_PUBLIC_AWS_COGNITO_REGION: string
    NEXT_PUBLIC_AWS_USER_POOLS_ID: string
    NEXT_PUBLIC_AWS_USER_POOLS_WEB_CLIENT_ID: string
    NEXT_PUBLIC_AWS_IDENTITY_POOL_ID: string
    NEXT_PUBLIC_AWS_ORDER_FILES_BUCKET: string
    NEXT_PUBLIC_AWS_ORDER_API_URL: string
    NEXT_PUBLIC_AWS_PROOF_READING_FILES_BUCKET: string
    NEXT_PUBLIC_AWS_PROOF_READING_API_URL: string
  }
}
